// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using theBakeShopApi.DBContext;

#nullable disable

namespace theBakeShopApi.Migrations
{
    [DbContext(typeof(ProductInfoContext))]
    [Migration("20220904150425_InitialDataseed")]
    partial class InitialDataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("theBakeShopApi.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d59959f6-2d8b-4e70-8b00-c05a4f87bf6f"),
                            ImageUrl = "assets/coffee-cake.jpg",
                            ProductDescription = "A coffee-flavored cake is typically baked in a circular shape with two layers separated by coffee butter icing, which may also cover the top of the cake",
                            ProductName = "Coffee Cake",
                            ProductPrice = 721m
                        },
                        new
                        {
                            Id = new Guid("e30c22b2-b15d-4bc3-bc88-10f5c06f4873"),
                            ImageUrl = "assets/banana-cake.jpeg",
                            ProductDescription = "A traditional banana cake is made like a butter cake with the addition of mashed banana for flavour.",
                            ProductName = "Banana Cake",
                            ProductPrice = 700m
                        },
                        new
                        {
                            Id = new Guid("e3d4b3cd-f463-42a0-b952-e57794cfdc96"),
                            ImageUrl = "assets/funfetti-cake.jpg",
                            ProductDescription = "Cake that has rainbow colored sprinkles baked into the batter.",
                            ProductName = "Funfetti Cake",
                            ProductPrice = 714m
                        },
                        new
                        {
                            Id = new Guid("c26ee15d-0075-449d-8f2e-0626d5f2ee29"),
                            ImageUrl = "assets/lemon-cake.jpg",
                            ProductDescription = "The 'lemony' flavour in a lemon cake is from the volatile oils which are present in the fruit's zest,(mainly nerol, limonene and citral).",
                            ProductName = "Lemon Cake",
                            ProductPrice = 600m
                        },
                        new
                        {
                            Id = new Guid("a6e4e208-f9bf-4088-b3ef-da009adc61f3"),
                            ImageUrl = "assets/black-forest-cake.jpg",
                            ProductDescription = "Black Forest gateau consists of several layers of chocolate sponge cake sandwiched with whipped cream and cherries.",
                            ProductName = "Black Forest Cake",
                            ProductPrice = 805m
                        },
                        new
                        {
                            Id = new Guid("dcb5f2bc-f01e-4304-9931-12aba8e24059"),
                            ImageUrl = "assets/cheese-cake.jpg",
                            ProductDescription = "The main, and thickest, layer consists of a mixture of a soft, fresh cheese, eggs, and sugar.",
                            ProductName = "Cheesecake",
                            ProductPrice = 781m
                        },
                        new
                        {
                            Id = new Guid("af8853f2-87f2-43d2-878f-cbd6c3b24926"),
                            ImageUrl = "assets/red-velvet-cake.jpg",
                            ProductDescription = "Red velvet cake is traditionally a red, red-brown, crimson, or scarlet-colored chocolate layer cake, layered with ermine icing.",
                            ProductName = "Red Velvet Cake",
                            ProductPrice = 721m
                        },
                        new
                        {
                            Id = new Guid("baea5f4f-f98c-496c-9ed9-34b7cf1f9190"),
                            ImageUrl = "assets/chocolate-cake.jpg",
                            ProductDescription = "Chocolate cake or chocolate gâteau is a cake flavored with melted chocolate, cocoa powder, or both.",
                            ProductName = "Chocolate Cake",
                            ProductPrice = 802m
                        },
                        new
                        {
                            Id = new Guid("267dd36e-c5af-4c8d-b5ad-3ae28dad37d9"),
                            ImageUrl = "assets/sansrival-cake.jpg",
                            ProductDescription = "Cake made of layers of buttercream, meringue and chopped cashews.",
                            ProductName = "Sans Rival Cake",
                            ProductPrice = 790m
                        },
                        new
                        {
                            Id = new Guid("d29d214a-1f8f-4423-8193-a8f963f046a1"),
                            ImageUrl = "assets/japanese-cotton-cake.jpg",
                            ProductDescription = "Is a variety of cheesecake that is usually lighter in texture and less sweet than North American-style cheesecakes.",
                            ProductName = "Japanese Cotton Cake",
                            ProductPrice = 721m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
